### ISSUE TITLE
Reviews don't show up

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#10]
Sorry to come up with that many bug reports, but I really like the website :)

I've published an app about 36h ago. The app showed up on the website pretty fast. The app then collected 5 reviews during the first day. Now, the next day, the overall rating of the app on the website has adjusted to be the same as on the official Ubuntu store, however, the app's details still say "No reviews yet"

(The example app I'm talking about here is Machines vs. Machines)

**Comment by bhdouglass** [comment]
@mzanetti no worries, more bug reports just means the site will continue to get better! Before the reviews were cached for 3 days, I've changed that to cache them for a day now, so you'll see the reviews faster now.
