### ISSUE TITLE
Images are in wrong order

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#11]
Small issues: I've changed the images on a game in the store, removing the existing one, adding two new ones and readding the existing one at the end. Now that the site has updated to it, it still shows the old image as the first one and appended the new ones at the end.

As the image order can be picked intentionally by the app developer, it would be nice if this site would reflect that ordering. (The example I'm talking about is again Machines vs. Machines)

**Comment by bhdouglass** [comment]
@mzanetti I believe I've fixed this issue, let me know how that looks!

**Comment by mzanetti** [comment]
yep, looks great. :)

**Comment by bhdouglass** [comment]
Awesome!
