### ISSUE TITLE
Can't open app in new tab

### ISSUE THREAD

**Issue by Nevon** [bhdouglass/ubuntu-appstore#12]
In [apps.html:14](https://github.com/bhdouglass/ubuntu-appstore/blob/master/src/static/app/partials/apps.html#L14):
```html
<div class="list-group-item clickable" ng-click="$state.go('app', {name: app.name})">
``` 

If you middle-click on an app in the list, a new tab will be opened with the app. However, the original tab also navigates to the app.

This makes it troublesome to browse through the apps. Ideally, I'd like the listing to work just the same way as regular links do.

**Comment by bhdouglass** [comment]
@Nevon a valid point, I've changed them to work like actual links. Let me know if you have any issues with them!
