### ISSUE TITLE
old entries in rss feed

### ISSUE THREAD

**Issue by BigButt** [bhdouglass/ubuntu-appstore#13]
Hello,

I'm constantly getting old apps listed on the rss feed.

**Comment by bhdouglass** [comment]
Could you give me an example of what you are seeing?

**Comment by BigButt** [comment]
Right now for instance I got 4 entries:
Green Mahjong 2.2.1    5 Months ago
GetThereDC 0.8        5 Months ago
Memories 1.20      5 Months ago
Terrarium 1.5     2 hours ago

I use the ownCloud 'News" client to fetch rss.

**Comment by bhdouglass** [comment]
Which page are you using as an rss feed? It could be that your feed reader is doing something weird since it's not an actual rss feed.

**Comment by BigButt** [comment]
ou. That's embarassing! Just realised that it's a third party site which generates the rss.
http://hogsmeade.lieberbiber.de/appstorediff.xml

But maybe you could offer your own rss feed?

**Comment by bhdouglass** [comment]
Haha, no worries, you had me a little confused there. An rss feed would be a good idea, I'll keep this issue open until I add one.

**Comment by BigButt** [comment]
Glad to hear.

**Comment by bhdouglass** [comment]
Just added an rss feed - http://feeds.feedburner.com/UbuntuTouchNewApps  Enjoy!

**Comment by BigButt** [comment]
That's great. Thanks a lot!
