### ISSUE TITLE
Bug in star ratings

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#14]
Example: https://appstore.bhdouglass.com/app/com.ubuntu.developer.thiebaud2001.commentcamarche

The summary says 4 stars. In the end it only has one review with 1 star though...

**Comment by bhdouglass** [comment]
It could be a bug in the actual appstore's api, since this app doesn't calculate the star rating. But since I changed it to stores all the reviews I can easily remedy that by doing my own average star calculation.

**Comment by bhdouglass** [comment]
I've made the change to do my own average star calculation, so that app's rating makes sense now.
