### ISSUE TITLE
Going to the next page should scroll to top

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#16]
Steps to reproduce:

* Open the app explorer in a small browser window, similar sized as a phone screen. The apps list will be a long single column list.
* scroll down to the bottom
* click on "next page"

=> The content will change, but you'll still be at the very bottom of the list. It should move up to the beginning automatically.

**Comment by bhdouglass** [comment]
I've had that idea in the back of my mind, never wrote it down which is probably why it hasn't been done yet. I'll get to it soon.

**Comment by bhdouglass** [comment]
Done, enjoy!
