### ISSUE TITLE
bug in pages selection

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#17]
Steps to reproduce:
* open uappexplorer.com
* Enter the "Apps" section
* Enter "google" into the search field
* scroll down to the bottom

=> The pages selection has a page 0. Clicking on it produces an error message.

**Comment by bhdouglass** [comment]
@mzanetti, thanks for finding this! I'll get it fixed soon.

**Comment by bhdouglass** [comment]
Just fixed this, thanks again!
