### ISSUE TITLE
Download apps to check whether they are webapps

### ISSUE THREAD

**Issue by nikwen** [bhdouglass/ubuntu-appstore#18]
Just like everyone I'm currently annoyed by the amount of webapps flooding the store. It would be really nice if this store frontend actually downloaded each app to check whether it is a webapp, a native app, a scope or a combination of more than one of them by looking at the package's manifest.json file.
If you need any help with understanding the latter, I'd be willing to help.

**Comment by bhdouglass** [comment]
I've been toying around with that idea some, just haven't gotten to far. Is there documentation somewhere on the manifest.json?

**Comment by nikwen** [comment]
Yes, the manifest.json format is indeed documented.
Check out http://click.readthedocs.org/en/latest/file-format.html#manifest. You will especially be interested in the hooks property. However, I found the documentation on that quite confusing.

You can find some information on specific hooks on the following pages:
https://developer.ubuntu.com/en/apps/platform/guides/content-hub-guide/
https://developer.ubuntu.com/en/apps/platform/guides/url-dispatcher-guide/
https://developer.ubuntu.com/en/apps/platform/guides/push-notifications-client-guide/
https://developer.ubuntu.com/en/apps/platform/guides/online-accounts-developer-guide/

These would allow specifying even more than just webapp/app/scope.

Here are some example files I could find:
App: https://github.com/nikwen/forum-app/blob/master/manifest.json
Webapp: http://bazaar.launchpad.net/~majster-pl/+junk/gPlus/view/head:/manifest.json
Scope: http://bazaar.launchpad.net/~cwayne18/+junk/urbandict-scope/view/head:/manifest.json

Webapp and scope: http://bazaar.launchpad.net/~cwayne18/+junk/urbandict-scope/view/head:/manifest.json
Scope with online accounts integration: https://github.com/rschroll/gmail-scope/blob/master/manifest.json.in
App and scope with push notifications: http://bazaar.launchpad.net/~libqtelegram-team/libqtelegram/telegram-app/view/head:/manifest.json.in

To check whether an app is a webapp, you probably also have to check out the desktop file.
App: https://github.com/nikwen/forum-app/blob/master/forum-app.desktop
Webapp: http://bazaar.launchpad.net/~majster-pl/+junk/gPlus/view/head:/GooglePlus.desktop

(Please note that it is guaranteed that a webapp has that "webapp-container" in the Exec attribute but that native apps do not necessarily have the "qmlscene". They can also specify a binary that should be executed.)

If you have any further questions, feel free to ask.

**Comment by bhdouglass** [comment]
Thanks for putting that all together!

So it looks to me like the way to tell if it is an app, scope, or app/scope is in the manifest, but to tell if an app is a webapp it will have webapp-container in the .desktop file.
Shouldn't be too difficult now that I've got the downloading/extracting sorted out.

**Comment by nikwen** [comment]
You're welcome. Thanks for looking into this.

To be more specific, the webapp-containter will be the first word in the Exec attribute. The rest of your description looks fine.

**Comment by bhdouglass** [comment]
Alright, I've got this up and running now. Take a look at https://uappexplorer.com/app/omgubuntu-scope.mreese for example. It's still processing a bunch of apps since it's pretty slow going.

**Comment by nikwen** [comment]
Nice! Thank you very, very much!

**Comment by bhdouglass** [comment]
You are welcome!
