### ISSUE TITLE
Apps page invariably change filter to "All types"

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#20]
Steps to reproduce bug:
1. In https://uappexplorer.com/, click on the app category
2. Observe that the apps page now filters correctly by "Apps".
3. Click on any app
4. Press < Uapp Explorer link which returns you to the apps page
5. Notice that the filter now has changed to "All "Types" instead of "Apps".

**Comment by bhdouglass** [comment]
Thanks for the heads up, just pushed a fix, so it's all good now!
