### ISSUE TITLE
Add more categories to the main page

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#21]
I think it would be nice to see categories like the following in the main page.

- Top 10 Apps [More]

This will motivate developers to make their app the best while rewarding them with the publicity they deserve.

- New Apps

This will give new apps developers a chance to be in the spotlight and bring more attention to their apps at this stage.

**Comment by bhdouglass** [comment]
Those sound like good ideas to me, I'll make it happen.

**Comment by krnekhelesh** [comment]
Wow thnx dude. Uapp Explorer rocks!

**Comment by bhdouglass** [comment]
I'm glad you like it! :)

**Comment by bhdouglass** [comment]
Just added a top apps section and new apps section to the main page, enjoy!

**Comment by krnekhelesh** [comment]
Sweet! Should help new developers get their apps noticed until it takes of and spread by word of mouth
