### ISSUE TITLE
Another bug with back button

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#22]
Sorry, but I couldn't think of a more useful title :P 

Steps to reproduce:
1. Open Apps and navigate to the 2nd page using the pagination options at the bottom
2. Click on an app
3. Press the < Uapp explorer button

Notice how it goes back to the Apps page. However it shows the apps from page 1 even though the pagination shows page 2.

**Comment by bhdouglass** [comment]
No worries about the title, the description was good. :smile:

Just fixed this, it should be good now.
