### ISSUE TITLE
2 versions of File Manager

### ISSUE THREAD

**Issue by fubarslayer** [bhdouglass/ubuntu-appstore#23]
Website and app show 2 versions of File Manager:
https://uappexplorer.com/app/com.ubuntu.filemanager
and
https://uappexplorer.com/app/com.ubuntu.developer.nskaggs.filemanager

However, the second version is not available via the official ubuntu store.

**Comment by bhdouglass** [comment]
It looks like one of them is for the x86 architecture and the other is for armhf. I'll have to make that clearer on the app's page.
