### ISSUE TITLE
Icon cache doesn't seem to update for updated apps

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#25]
We changed the application icon of Podbird in v0.6 that was released yesterday and after a day, uappexplorer has got the latest reviews, changelog, screenshots and pretty much everything except for the app icon which is still the old one being shown.

https://uappexplorer.com/app/com.mikeasoft.podbird

**Comment by krnekhelesh** [comment]
It seems to have updated today afternoon. I guess I just to wait a bit longer for the icon cache to be refreshed.

**Comment by bhdouglass** [comment]
The icon should be updated immediately, except that I have the browser caching the image for a few days. I'll have to change it so it gets the new icon when it's available.

**Comment by bhdouglass** [comment]
I added an icon versioning the other day that should prevent this from happening in the future.
