### ISSUE TITLE
Feature Request: Show more detailed stats

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#26]
I am not sure if this information is provided by the store's public API, but just putting out a request,

- It would nice to see more the download numbers of an app..it doesn't have to be specific..just something like 500-1000 or >2000 etc..

- With the reviews that we have, can we use that to shows stats like,

Avg. Rating: 4.5
Total number of reviews: 34
5 star reviews: 20
4 star reviews: 10
3 star reviews: 0
2 star reviews: 3
1 star reviews: 1

Preferable the above in a more graphical manner.

Just an idea.

**Comment by bhdouglass** [comment]
Unfortunately the official store's api doesn't provide the number of downloads, but I can add a star breakdown (it's been on my todo list).

**Comment by bhdouglass** [comment]
I just added the star breakdown, let me know how it works for you!

**Comment by krnekhelesh** [comment]
It is brilliant! I have just one small concern in that while it is nice to see all these information for an app, it could be presented a bit more consistently. For example, on the desktop I notice that the app changelog, support, etc are shown on the right side as a row of tabs, while most of the other content are shown in a column. It could use a designer's touch. Perhaps someone from the community could help propose a design with a better layout. Just my 2 cents.

**Comment by bhdouglass** [comment]
I'll give the design some thinking over. I'm certainly open to suggestions and/or contributions.
