### ISSUE TITLE
[UT Web App] Add screenshots of the web app running on the device

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#27]
Congrats on adding the store to the Ubuntu Touch Store. A great way to promote another way of exploring and installing apps. Inception :) I think it would help users if you add screenshots to the web app in the Ubuntu Touch store. Preferable screenshots of the web app running on the device. I have attached some screenshots of it running on the device to help out.

![uapp4](https://cloud.githubusercontent.com/assets/761845/7440079/296f3a2a-f09f-11e4-8f7e-5169d3fc5ebd.png)
![uapp3](https://cloud.githubusercontent.com/assets/761845/7440081/29713c4e-f09f-11e4-8785-d2eb90b93d36.png)
![uapp2](https://cloud.githubusercontent.com/assets/761845/7440080/29710756-f09f-11e4-9e6a-f258885038f0.png)
![uapp](https://cloud.githubusercontent.com/assets/761845/7440082/2979a88e-f09f-11e4-8bff-6a9be997db56.png)

**Comment by bhdouglass** [comment]
Thanks for the screenshots, just uploaded them. I only have Ubuntu Touch on a table so my screenshots wouldn't have looked good at all. I'm noticing a lot of Podbird in them :)

**Comment by krnekhelesh** [comment]
Hey I took better screenshots with oliver's new web container. Do you mind replacing the current screenshots with the ones I have uploaded at https://www.dropbox.com/s/c4gaa4hojmt43z4/Uapp%20Explorer.zip?dl=0  .. .also I realised that having too many Podbird screenshots is not correct since we are advertising about uappexplorer and not podbird. Sorry about that :P

**Comment by bhdouglass** [comment]
Thanks for the updated screenshots!
I don't mind all the Podbird, it's got a great icon. :)
