### ISSUE TITLE
[UT Web App] Make web app look slightly more native

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#28]
I am not sure if you have tried out [Ogra's g+ plus app](https://uappexplorer.com/app/google-plus.ogra) but it nicely integrates with Ubuntu Touch. It would be nice to see the uapp explorer web app do that by fixing the following things,

- Add a menu button at the top left corner instead of the right **and** use that to be able to navigate between apps, web app, scopes and games.
- Use ogra's web container which will give you support for the radial bottom edge that you see in the g+ app.
- Bonus points if you could theme your app to look like a native ubuntu touch app. What I mean by theming your app is not the color scheme but rather the UI styles of the drop down menu, tabs etc. For the most part, I already see that you use the ubuntu shape in several places.

All these are just suggestions since I personally think that having Uapp explorer as a web app provides a good competition and alternative to the official UT store and promotes innovation. Great work!

**Comment by krnekhelesh** [comment]
Perhaps you could take motivation from the official UT store on their layouts to present more information efficiently on the mobile device. For instance, I notice that UT Store is able to show 6 top apps in a very efficient way with all the necessary details as shown below,

![uapp5](https://cloud.githubusercontent.com/assets/761845/7440135/c0b997e8-f0a1-11e4-8bc5-a157f65003be.png)

**Comment by bhdouglass** [comment]
I want to make sure uApp Explorer stays distinct from the official store, but making a mobile grid view is definitely on my todo list. I'll probably switch over to Ogra's alternative webapp container, it seems much more hackable. Then I'll get to work on making the experience more like an Ubuntu Touch app, I agree it could use some work. I'm not entirely sold on the idea of theming it to be native right now, but we'll see how things progress.

**Comment by bhdouglass** [comment]
Just switched to Ogra's webapp container, let me know how that works!

**Comment by krnekhelesh** [comment]
It is really nice! Perhaps we should close this bug and use bug reports which are more specific on what needs to be fixed (if any).

**Comment by bhdouglass** [comment]
I concur, closing this out for future tickets
