### ISSUE TITLE
[UT Web app] Improve space utilization of the reviews on the mobile form factor

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#30]
I have attached screenshot of uapp explorer's and the official ut store review system on the mobile form factor and I feel that the space utilization of Uapp explorer can be improved. To be honest, in terms of visual design I actually like Uapp explorer's implementation. It is just the margins that should be improved.

My suggestions are,
* Reduce the left and right margins a bit
* Currently the review description are left-aligned to the author label. But I think left-aligning it to the left of the profile pic might be more efficient.
* Reduce font size of the author label a tiny bit.

I will try reporting bugs similar to this which are very specific to help improve it.

![improve-review](https://cloud.githubusercontent.com/assets/761845/7523093/b1036caa-f4f9-11e4-9ae2-59cdbecaf047.png)
![improve-review2](https://cloud.githubusercontent.com/assets/761845/7523110/d0dd6dc8-f4f9-11e4-9aad-c3b6193fbb8d.png)

**Comment by bhdouglass** [comment]
Thanks for the suggestions, I think I'll move the review and author name to the left (under the icon). And reduce the margins, they are quite excessive.

**Comment by bhdouglass** [comment]
I just uploaded an update for this, moved the review text to the far left, reduced the size of the author name, and reduced the right margin. Let me know what you think!

**Comment by krnekhelesh** [comment]
Much better! Thanks for the quick fix.
