### ISSUE TITLE
Better design of the detailed stats

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#31]
Here is a screenshot of the detailed stats shown on the google play store which is a bit more efficient and elegant in my opinion for the following reasons,

* Uses less vertical space
* Average rating is shown big and clearly
* An idea of how many people rated 5 star, 4 star etc etc

Would it be possible to accommodate this in Uapp explorer's stat system?

![reviewsystem](https://cloud.githubusercontent.com/assets/761845/7523296/19c95640-f4fb-11e4-8537-c441a9ef9bdc.png)

**Comment by bhdouglass** [comment]
Funny, this is what I used for my inspiration! Making it more compact would be good. If you hover over the bars you'll see how many users left reviews at that star level. Obviously that doesn't work as well on mobile, so I'll make a change for mobile.

**Comment by krnekhelesh** [comment]
I have to admit that up until I never knew that hovering over the bars will shows how many users left reviews at that star levels.

**Comment by bhdouglass** [comment]
Just implemented an improved version of the review stats, let me know what you think!

**Comment by krnekhelesh** [comment]
Ooh I like the new design..address the issues that I brought up nicely like knowing how much people have rated 5 star, 4 star etc.

**Comment by bhdouglass** [comment]
:smile:
