### ISSUE TITLE
Grid behavior misbehaves in some configurations

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#32]
I have a standard 1920x1080 laptop where I had firefox occupying half of the screen as shown [here](https://i.imgur.com/7yTFwIb.png) and as you can see there is sufficient space to show a 3rd column.

**Comment by bhdouglass** [comment]
It must be "tablet sized", which I've been meaning to make have three columns. Weird though that it doesn't fill the space evenly, even with 2 columns.

**Comment by bhdouglass** [comment]
Just fixed this, it'll show in two full columns now.

**Comment by krnekhelesh** [comment]
Yup it seems fixed. It does expose 2 tiny ui (text overlapping) bugs, but I will report them as new ones.
![tabletview](https://cloud.githubusercontent.com/assets/761845/7539208/bd6868ea-f5a5-11e4-853d-48b0164db515.png)
