### ISSUE TITLE
Minor UI Quirks

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#34]
The screenshot below show 2 minor UI quirks,
- Lines not aligning with one other
- Reviewer name extending too much.

The UI is becoming cleaner, better and efficient by the day. Thanks for accepting the suggestions.

![reviews](https://cloud.githubusercontent.com/assets/761845/7539419/2861b29a-f5a7-11e4-8d9f-a5a0f26cc28b.png)

**Comment by krnekhelesh** [comment]
![lineerror](https://cloud.githubusercontent.com/assets/761845/7539563/1ebef67a-f5a8-11e4-8cf9-8346ca41fd3e.png)

**Comment by bhdouglass** [comment]
I just implemented hiding extra long parts of a reviewer's name and I removed the lines under the categories on desktop (didn't really make much sense to keep them).

I'm still trying to figure out the best way to keep the lines at the same height, I'd agree it would look much better.

**Comment by krnekhelesh** [comment]
Could you also remove the lines under the categories on the UT web app? It has the same issue as the desktop one. Let me know if you want a screenshot.

**Comment by bhdouglass** [comment]
I left it on the mobile view because it made sense to have a separator. Leaving it in also keeps it consistent with the rest of the app.

**Comment by bhdouglass** [comment]
I made the separators uniform just now, enjoy!

**Comment by krnekhelesh** [comment]
The uniform separators make it look so much better. Nice work!

**Comment by bhdouglass** [comment]
Glad you like it! It makes it look much cleaner.
