### ISSUE TITLE
[UT Web App] Add HomePage button to the radial bottom edge menu

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#36]
Would it be possible to add a "HomePage" action button to the radial bottom edge menu as sometimes it comes in handy to quickly go to the uappexplorer.com rather than pressing the back button a couple of times.

**Comment by bhdouglass** [comment]
I like that idea, I'll have to see about implementing it.

**Comment by bhdouglass** [comment]
Just uploaded this feature, do you mind snapping a new screenshot of the menu?

**Comment by krnekhelesh** [comment]
Sure here is a screenshot of the new home button in action. If there are any other specific testing or screenshot you need on the phone, do let me know. Happy to help.

![home](https://cloud.githubusercontent.com/assets/761845/7554841/859416d2-f738-11e4-85fe-935a225866bc.png)

**Comment by bhdouglass** [comment]
Perfect, thanks!
