### ISSUE TITLE
QR code not always generated

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#37]
I just discovered the QR code feature on the site. However, it seems to fail on some apps for me. I haven't been able to figure a pattern on when it works and when it doesn't. I think it's related to dashes in the appId, as well as very long appId seem to break it too.

**Comment by bhdouglass** [comment]
Is there a consistent example of this? I'm assuming it is something to do with the length of the app name.

**Comment by mzanetti** [comment]
Working:
com.ubuntu.telegram
dekko.dekkoproject
com.zeptolab.cuttherope.full

Broken:
com.ubuntu.developer.mzanetti.machines-vs-machines
com.ubuntu.developer.majster-pl.utorch
com.ubuntu.developer.mzanetti.getmewheels2
com.ubuntu.developer.gcollura.saucybacon

**Comment by bhdouglass** [comment]
Thanks, I'll get this fixed!

**Comment by bhdouglass** [comment]
Just fixed this, it was an issue with the name being too long.
