### ISSUE TITLE
Show apps made by the developer when looking at an app in detail

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/ubuntu-appstore#38]
When clicking on an app to see more details about it, it would be nice to add a row of other apps made by the same developer (if more are available). This is something most other app stores do as well for good reason.

**Comment by bhdouglass** [comment]
Just added this under the screenshots!

**Comment by krnekhelesh** [comment]
You do realize that because you fixed all my bugs, I have nothing much to do except just use the app store ;P

**Comment by bhdouglass** [comment]
What??? People actually use this thing??? :)

Now that the bugs are out of the way, it is on to new features!
