### ISSUE TITLE
Cannot filter packages by architecture

### ISSUE THREAD

**Issue by jamestait** [bhdouglass/ubuntu-appstore#5]
The Click Package Index allows filtering of results by the client architecture by providing the X-Ubuntu-Architecture header [0] but this doesn't seem to be possible in ubuntu-appstore.

[0] https://wiki.ubuntu.com/AppStore/Interfaces/ClickPackageIndex#Client_Architecture

**Comment by bhdouglass** [comment]
Just added a new filter option for this, enjoy!
