### ISSUE TITLE
Cannot filter packages by framework

### ISSUE THREAD

**Issue by jamestait** [bhdouglass/ubuntu-appstore#6]
The Click Package Index allows filtering of results by the framework(s) the Package requires, by passing the X-Ubuntu-Frameworks header [0], but this doesn't seem to be possible in ubuntu-appstore.

[0] https://wiki.ubuntu.com/AppStore/Interfaces/ClickPackageIndex#Frameworks

**Comment by bhdouglass** [comment]
Added this in addition to the architecture filter, thanks for the suggestion!
