### ISSUE TITLE
Should use the Departments API for categories and filter-by-category

### ISSUE THREAD

**Issue by jamestait** [bhdouglass/ubuntu-appstore#7]
The Click Package Index provides a Departments API [0] that will return a full hierarchical Department tree at its root, and details of a specific Department and its Packages and Highlights given the Department slug. Currently it looks like ubuntu-appstore is querying the retrieved list of packages locally.

[0] https://wiki.ubuntu.com/AppStore/Interfaces/ClickPackageIndex#Departments

**Comment by bhdouglass** [comment]
This has been on my to do list, shouldn't be to hard to add.

**Comment by bhdouglass** [comment]
@jamestait just added departments to the appstore rather than pulling them off the packages like before.
