### ISSUE TITLE
Add scope:// links

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#8]
It would be great if the Ubuntu App Store web ui had links to the official store. While it currently isn't entirely possible to directly open the app's preview, it is still possible to filter search results by the name using for example:

scope://com.canonical.scopes.clickstore?q=Machines%20vs%20Machines

Someone viewing the website on a phone could then just tap this and have the app installed with 2 more clicks.

**Comment by bhdouglass** [comment]
@mzanetti I didn't know you could do that! I just implemented this, let me know if you have any issues with it.

**Comment by mzanetti** [comment]
Working perfectly fine on my phone (At least as good as the store allows it)
