### ISSUE TITLE
Clicking the author brings you to the main page

### ISSUE THREAD

**Issue by mzanetti** [bhdouglass/ubuntu-appstore#9]
When viewing an app, there's the author's name as a link. Clicking it brings you back to the unfiltered main page. Instead it'd be great if it would present a list of apps published by that same person.

**Comment by bhdouglass** [comment]
That's what its *supposed* to do, must have broke somewhere.

**Comment by bhdouglass** [comment]
I just fixed this, now the author links are useful again.
